### ISSUE TITLE
`Connection::poll` order

### ISSUE THREAD

**Issue by dvc94ch** [quinn-rs/quinn#1094]
This can cause an `Event::Connected` to be delivered after an `Event::Stream`. I'm not sure if this is intended behaviour because of 0-rtt, but for my application that doesn't use 0-rtt it means I have to buffer stream events until `Event::Connected` happens. Reversing the order presumably would deliver an `Event::ConnectionLost` before the stream data has finished processing, which is also not ideal. Maybe it would be useful to split `poll` into a  `poll_stream` and `poll_connection` and let the application handle it?

```rust
pub fn poll(&mut self) -> Option<Event> {
    if let Some(event) = self.streams.poll() {
        return Some(Event::Stream(event));
    }
    if let Some(x) = self.events.pop_front() {
        return Some(x);
    }
```

**Comment by Ralith** [comment]
Hmm, I'm not a huge fan of adding to our already awkwardly large collection of methods a quinn-proto user has to understand to drive things properly, or of requiring many downstream users to duplicate similar logic.

0-RTT can indeed legitimately cause stream activity before the connection is established, and buffering until the connection is fully established is a reasonable way to handle 0-RTT. Note that Quinn enables 0-RTT by default at the protocol layer, so even if your code never uses it intentionally, if you operate on the internet you might encounter third-party code that does so. If this is undesirable, we could add a config flag to disable it explicitly.

Regardless, I sympathize with the desire to have a more natural event ordering. I think we can solve this non-disruptively by moving more events out of `self.events`; for example, connection errors could be given dedicated storage that we check at the end of `poll`. If we remove `impl From<ConnectionError> for Event`, we only see four locations that would need to be updated, so that might be pretty easy.

**Comment by Ralith** [comment]
Oh, cool! I'm glad our abstract crypto stuff is getting some use. Correcting the ordering of reported events seems like the way to go, then.

**Comment by djc** [comment]
@dvc94ch would be nice if you can make your noise implementation available as a separate crate, I bet other people might be interested in it, too.

**Comment by Ralith** [comment]
Opened https://github.com/quinn-rs/quinn/pull/1100 to address this.
