### ISSUE TITLE
Suggestion: infallible `TransportConfig` APIs

### ISSUE THREAD

**Issue by connec** [quinn-rs/quinn#1176]
I'm currently using `quinn` for the transport layer in another library. This has generally been pretty smooth, and is definitely helped overall by the granularity of error types in `quinn` 👍 

However, I'm finding the `TransportConfig` API particularly awkward to work with, since many methods can fail with `ConfigError::OutOfBounds` (e.g. [`quinn::TransportConfig::max_concurrent_bidi_streams`](https://docs.rs/quinn/0.7.2/quinn/struct.TransportConfig.html#method.max_concurrent_bidi_streams)). Since `ConfigError` non-exhaustive I can't easily wrap it without some kind of catch-all variant, or exposing `quinn::ConfigError` from my library.

Since all the fallibility comes from converting to `VarInt`s, would you be open to adding relevant 'lower level' methods to `TransportConfig` that would accept a `VarInt` and be infallible, so that consumers can do their own validation/sanitisation?

Some other options I considered, but I don't think really solve the issue:

- Make `quinn::ConfigError` exhaustive. That makes it easier to hide `quinn::ConfigError`, but doesn't really help with infallible use (e.g. if I want to simply clamp out-of-bounds values, I'll still end up `unwrap`ping a `ConfigError`, and/or dealing with other variants (with `unreachable` etc.)).
- Use a specific `OutOfBounds` error, rather than the `ConfigError` enum. That has the same issue as above, though I'd be more comfortable `unwrap`ping it.

**Comment by Ralith** [comment]
Thanks for the issue! I'm fine with these methods being modified to consume `VarInt` directly, for the reasons you outline. `0u32.into()` isn't too bad for people who are hardcoding these values, so I'm not inclined to bother with multiple variants, though maybe `impl Into<VarInt>` wouldn't be too bad.

**Comment by connec** [comment]
That makes sense, I had also thought about changing the signature to `impl TryInto<VarInt>`, returning the associated error – that way you can do an empty match on `Infallible` (and hopefully one day [`Result::into_ok`](https://doc.rust-lang.org/stable/std/result/enum.Result.html#method.into_ok)). That could be a bit much type gymnastics though.

Also, what do you think about [`max_idle_timeout`](https://docs.rs/quinn/0.7.2/quinn/struct.TransportConfig.html#method.max_idle_timeout)? It's a shame to lose `Duration`, and it's not obvious from the current name that a raw value would be in milliseconds.

**Comment by Ralith** [comment]
Hmm, good question. We can't realistically have both standard, user-friendly types and correctness by construction, and switching back and forth between the two for different methods might be a bit weird. It'd definitely be nice not to force an `unwrap` on people. An `IdleTimeout` implementing `TryFrom<Duration>` would be elegant, but maybe gratuitously weird? I'd be interested to hear @djc and @Matthias247's thoughts.

**Comment by djc** [comment]
I'd be okay with an IdleTimeout newtype.

**Comment by Matthias247** [comment]
Some thoughts:
- APIs accepting `VarInt`s instead of other values sounds great
- For times, I think I would prefer keeping `Duration` and an error. Otherwise people always have to look up what the other thing is about.
- I don't think requiring external code to pass only good values and simply `.unwrap()` if that doesn't work is too bad of a solution either. If you want to forrward an error and box it, something along `anyhow::Errror` works good in my experience. It's not like the parameters are set very often and with highly different values that are dynamically derived.
- I think in general quinn `Config` structs are a bit "special", because they don't act like usual `Builder`s (where the `Builder` has only mutable setters, and the built config is fully immutable). Applies even more so to `ServerConfig/ServerConfigBuilder`, where you for some use-cases have to `.build()` a config first, and then afterwards still have to mutate it. In some future revision I would probably like to see all of those to be cleaned up to use regular `Builder`s.
- If you move to a `Builder`, you  always have the chance to postpone any error reporting to the final `.build()` call. That can be used to reduce the amount of error handling code an application requires - but also obfuscates a bit more which config is actually invalid. So both appraoches have their merit.

**Comment by connec** [comment]
Some possibilities (focusing on `max_idle_timeout`):

```rust
impl TransportConfig {
    // Current, e.g.
    // ```
    // config.max_idle_timeout(Some(duration))?;
    // config.max_idle_timeout(None).unwrap();
    // ```
    pub fn max_idle_timeout(&mut self, value: Option<Duration>) -> Result<&mut Self, ConfigError> { ... }

    // `Into<VarInt>`-based, e.g.
    // ```
    // config.max_idle_timeout(0_u8);
    // config.max_idle_timeout(VarInt::try_from(u64::try_from(duration.as_millis())?)?); // gross, but you get the idea
    // ```
    pub fn max_idle_timeout(&mut self, value: Into<VarInt>) -> &mut Self { ... }

    // `TryInto<VarInt>`-based, e.g.
    // ```
    // config.max_idle_timeout(0_u8).into_ok(); // unstable API, but same effect can be achieved in other ways
    // config.max_idle_timeout(VarInt::from(123_u32)).into_ok();
    // config.max_idle_timeout(Duration::from_secs(123)).unwrap(); // needs impl TryFrom<Duration> for VarInt
    // ```
    pub fn max_idle_timeout<V>(&mut self, value: Option<V>) -> Result<&mut Self, V::Error>
    where
        V: TryInto<VarInt>
    {}

    // Newtype-based, e.g.
    // ```
    // enum IdleTimeout { None, Milliseconds(VarInt) } // e.g.
    //
    // config.max_idle_timeout(0_u8.into()); // needs `From<u8> for IdleTimeout`
    // config.max_idle_timeout(duration.try_into()?); // needs `TryFrom<Duration> for IdleTimeout`
    // config.max_idle_timeout(option.try_into()?); // needs `TryFrom<Option<impl TryInto<IdleTimeout>>> for IdleTimeout`
    // ```
    pub fn max_idle_timeout(&mut self, value: IdleTimeout) -> &mut Self { ... }
}
```

Having written that out, I'm finding the newtype-based approach the nicest:

- Completely separates conversion errors from the configuration API.
- Allows more flexibility in conversions.
- `enum` still makes it clear that the `VarInt` represents milliseconds, and allows `None`.
- It would be quite self-describing in documentation.

However, I could understand an argument that it's a bit much machinery for such a small part of the API 😄

**Comment by djc** [comment]
We could also add a (well-documented) TryFrom<Duration> for VarInt.
