### ISSUE TITLE
WebTransport in Chrome throws ALPN error

### ISSUE THREAD

**Issue by Pascualex** [quinn-rs/quinn#1266]
I've checked this closed issue #934 and it looks like the problem persists.

Following the [IETF draft specification](https://tools.ietf.org/id/draft-vvv-webtransport-quic-02.html#rfc.section.9.1) I've set the "wq-vvv-01" ALPN in my server. Just to be completely sure, I've checked the values of my `alpn_protocols` and they are in fact the expected sequence: `0x77 0x71 0x2d 0x76 0x76 0x76 0x2d 0x30 0x31`.

Chrome throws the following error: `peer doesn't support any known protocol`.

It isn't completely broken since when I don't specify any ALPN the error changes to: `no application protocol`.

I'm testing this with [Chrome Beta](https://www.google.com/chrome/beta/), but version 97 will go out in January with WebTransport support, so this use case may start to be more common.

**Comment by Ralith** [comment]
That draft expired last January. It looks like the current WebTransport draft is [draft-ietf-webtrans-http3](https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3), which builds on top of h3 rather than raw QUIC. Presumably Chrome is therefore using the h3 ALPN. If in doubt, wireshark should be able to tell you what ALPNs the client is offering.

**Comment by Pascualex** [comment]
I had tried a bunch of ALPNs, including `h3-27`, `h3-29` and `h3-32` but not the simple `h3`.

It's working now, thank you.

**Comment by Ralith** [comment]
> Chrome throws the following error: peer doesn't support any known protocol.

Incidentally, this isn't actually a Chrome error, but a rustls error being piped all the way back down to the client. Pretty neat that that's being propagated gracefully!
