### ISSUE TITLE
`libc::sendmmsg` is not available on old Android phones

### ISSUE THREAD

**Issue by link2xt** [quinn-rs/quinn#1503]
`sendmmsg` was added in Linux 3.0 and `recvmmsg` was added in Linux 2.6.33 according to their man pages.

It is used in
https://github.com/quinn-rs/quinn/blob/389d7ce5067fbef460f0730861340b15f13d4803/quinn-udp/src/unix.rs#L197

**Comment by djc** [comment]
Ugh, how old are these Android phones that you are targeting?

If it's not too much complexity, we're happy to take a PR to enable support on older kernels.

**Comment by Ralith** [comment]
Fixed by #1504.

**Comment by mxinden** [comment]
I wonder whether the patch merged via https://github.com/quinn-rs/quinn/pull/1504 is worth the trouble it is causing. In other words, I would like to discuss switching back to calling `libc::recvmmsg` instead of `libc::syscall(libc::SYS_recvmmsg`.

- On Android x86 calling `libc::syscall(libc::SYS_recvmmsg` instead of `libc::recvmmsg` leads to a SECCOMP panic. See https://github.com/quinn-rs/quinn/pull/1964.
- At this point Android API Level 16 is [12 years old](https://apilevels.com/). Are there any known use-cases running `quinn` on such old devices? With the security concerns alone, I don't see a use-case outside a completely isolated environment.
- Android 4 (up to API Level 20) has been end-of-life'd 01 Oct 2017. Should `quinn` support an OS that has been unsupported for 7 years?

//CC @link2xt, @flub and @dignifiedquire (since you have been active on https://github.com/deltachat/deltachat-core-rust/pull/4007)
