### ISSUE TITLE
i wanna use quinn_proto but there's few document

### ISSUE THREAD

**Issue by zzwxh** [quinn-rs/quinn#1619]

**Comment by djc** [comment]
What is your use case? What are you having trouble with? What documentation have you looked at? Why do you want to use quinn-proto instead of quinn?

**Comment by zzwxh** [comment]
i don't wanna bind myself to tokio or rust futures/async feature
i wanna create my own io library

**Comment by zzwxh** [comment]
found few document on [docs.rs/quinn_proto](https://docs.rs/quinn-proto/latest/quinn_proto/)

**Comment by djc** [comment]
Have you looked at the README? It links to a bunch of examples and a book that explains some of the core concepts.

In general, this issue is not actionable. Feel free to file issues with specific questions after you've read through the relevant documentation, or join our Discord channel (also linked in the README) to ask questions there.

In both cases, generic remarks like "there's few documents" are pretty unhelpful.

**Comment by zzwxh** [comment]
i found no discord link or example without async.
https://github.com/quinn-rs/quinn.
i found https://github.com/quinn-rs/quinn/tree/main/quinn-proto/src/tests and docs.rs doc.

**Comment by djc** [comment]
Sorry, there's a Matrix link but it's the same underlying channel. Discord: https://discord.gg/SGPEcDfVzh.

That's right, for most people (especially people with seemingly little familiary with the space -- it seems like you might be in this category), we definitely advise the use of the higher-level API (which works with any async runtime).
