### ISSUE TITLE
Update package ring to 0.17 for Windows arm64 support

### ISSUE THREAD

**Issue by lhyzf** [quinn-rs/quinn#1678]
see https://github.com/briansmith/ring/issues/1614

**Comment by djc** [comment]
We expose both *ring* and rustls as part of the public API, so in order to update *ring* to 0.17 we'll need to make a semver-incompatible bump to the API. However, I expect we'll also get a semver-incompatible rustls release in a few weeks from now so I think we'll want to wait until we can do both.

**Comment by dignifiedquire** [comment]
rustls is already using `ring@0.17` on the latest `rustls@0.21.8`, which is a bit unfortunate, as this means currently `quinn` pulls in two versions of ring

**Comment by djc** [comment]
Yup -- I don't think there's much that can be done, hopefully rustls 0.22 will be published soon.

**Comment by PikuZheng** [comment]
any progress?

**Comment by Ralith** [comment]
You can track the current progress at https://github.com/quinn-rs/quinn/pull/1715, where you previously commented.

**Comment by Ralith** [comment]
Quinn 0.11 has been released, using ring 0.17.
