### ISSUE TITLE
quinn is failing `zerortt` interop

### ISSUE THREAD

**Issue by larseggert** [quinn-rs/quinn#1929]
See https://interop.seemann.io/?run=2024-07-21T16:31, the entire line has red `Z`s.

**Comment by Ralith** [comment]
This is a false negative due to https://github.com/quic-interop/quic-interop-runner/issues/398 and the interaction between Quinn's PLPMTUD and the test case's choice to use total packet payload sizes as a heuristic for whether 0-RTT is being used as much as expected. https://github.com/quinn-rs/quinn-interop/pull/10 will work around the quic-interop behavior.
