### ISSUE TITLE
EndpointBuilder is not easily chainable to the end

### ISSUE THREAD

**Issue by imp** [quinn-rs/quinn#333]
`EndpointBuilder` methods are taking and returning `&mut self`, while the final constructors (`bind` and `with_socket`) take `self`. So that the next code doesn't compile

```rust
let (driver, endpoint, incoming) = quinn::Endpoint::builder()
    .logger(logger)
    .reactor(reactor)
    .bind("localhost")?;
```

This is not possible however, since `bind` takes `self`, while all the builder mutators are returning `&mut self` ensuring `error[E0507]: cannot move out of borrowed content`.

Would it be possible to change the API to make chaining possible?

Option A would be to make mutators get and return `self`
Option B(-etter), would be to make `bind` take `&self` (and thus become a non-consuming constructor)

The downside of course is that would be a breaking change, but I thought to bring it up to discussion early, before API is stabilized.

**Comment by djc** [comment]
Why do you prefer option B? I think I'm leaning towards option A because that would require the caller to clone the builder explicitly rather than the builder implicitly doing the same in the case of a ref-taking bind(). (Assuming we can easily derive Clone on Endpoint Builder.)

**Comment by Ralith** [comment]
I consciously chose the `&mut`-style builder convention for Quinn because it makes it easy to make conditional changes to a builder. For example:

```rust
let mut config = ServerConfigBuilder::default();
if args.enable_keylog { config.enable_keylog(); }
```

`EndpointBuilder` itself doesn't presently have much that really demands that, but I'd prefer to use a consistent convention, and this seems like the least of assorted evils. Clonable builders/build-by-reference is an interesting idea; it's not trivially cheap, since the config structs are held by value, but the config structs aren't *that* huge. One issue is that `TokenKey` and `SigningKey`, held by `ServerConfig` and `EndpointConfig` respectively, are not `Clone`; this could be resolved by storing plain byte arrays for those keys, which would also simplify the interface somewhat, though it'd require their data to be duplicated inside `Endpoint` for use.

**Comment by djc** [comment]
It's not even clear to me whether the `TokenKey` should be shared by two `Endpoint`s when the `EndpointBuilder` is cloned...

**Comment by djc** [comment]
Since 7bf24093c51fac92b2f49d15718b182799827a13, builder types have become cloneable. So we can now at least think about having `with_socket()` take a `&self` instead of `self`.

**Comment by Ralith** [comment]
#1213 removed `EndpointBuilder` entirely, so this is now moot.
