### ISSUE TITLE
H3: drive quic in the same task as the connection

### ISSUE THREAD

**Issue by stammw** [quinn-rs/quinn#708]
Not sure what the best way forward would be. But using two tasks seems potentially wasteful. @Ralith any thoughts?

_Originally posted by @djc in https://github.com/djc/quinn/pull/697#discussion_r406143296_

**Comment by Ralith** [comment]
From a high level perspective, the simplest approach here would be to construct a future equivalent to what you'd get from `join!(quinn_driver, h3_driver)`, or embed the quinn driver future inside the h3 driver future in an equivalent fashion. Does that make sense?

**Comment by Ralith** [comment]
This is complicated by the fact that quinn implicitly spawns the driver future internally. That happens when a handshake begins, which is intentionally not synchronized with the application accepting new connections, as otherwise incoming connections could time out when the application is exerting backpressure.

A simple hack might be to expose a hidden interface or configuration option through which quinn-h3 can specify a `Fn(impl Future) -> impl Future` to wrap the driver. Would be nice to be more graceful than that, though.

**Comment by djc** [comment]
It might be that hyper also would prefer to spawn its own tasks for this, so I think some kind of helper method would be useful indeed.
