### ISSUE TITLE
Confusion in docs how to send a datagram

### ISSUE THREAD

**Issue by Ploppz** [quinn-rs/quinn#936]
First I was looking at [`Connection::send_datagram`](https://docs.rs/quinn/0.6.1/quinn/generic/struct.Connection.html#method.send_datagram). It's not an async function which makes me think that it cannot actually send the datagram. So I would think that I need to call some other function to actually make the datagram get sent, but I haven't found one.

Looking at its implementation brought me to [`quinn_proto::Connection::send_datagram`](https://docs.rs/quinn-proto/0.6.1/quinn_proto/generic/struct.Connection.html#method.send_datagram)

The docs say:

> The returned DatagramSender must be used to actually send a datagram. This allows the caller to defer materializing a datagram until one can be sent immediately without redundant checks

But it returns `()`.

**Comment by Ralith** [comment]
Hi, thanks for the report! The `quinn_proto` docs you cite are outdated, and we should fix that. `Connection::send_datagram` does actually send the datagram; it's not `async` because there is no backpressure for datagrams, so it's up to you to ensure you don't send more than the peer is willing/able to handle.

**Comment by Ploppz** [comment]
Ah, it does make sense that sending an unreliable message takes little time / no blocking. Thanks.
